export const demo_data = [
  {
    id: 100695,
    node_id: "MDEwOlJlcG9zaXRvcnkxMDA2OTU=",
    name: "drupal",
    full_name: "drupal/drupal",
    private: false,
    owner: [Object],
    html_url: "https://github.com/drupal/drupal",
    description:
      "Verbatim mirror of the git.drupal.org repository for Drupal core. Please see the https://github.com/drupal/drupal#contributing. PRs are not accepted on GitHub.",
    fork: false,
    url: "https://api.github.com/repos/drupal/drupal",
    forks_url: "https://api.github.com/repos/drupal/drupal/forks",
    keys_url: "https://api.github.com/repos/drupal/drupal/keys{/key_id}",
    collaborators_url:
      "https://api.github.com/repos/drupal/drupal/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/drupal/drupal/teams",
    hooks_url: "https://api.github.com/repos/drupal/drupal/hooks",
    issue_events_url:
      "https://api.github.com/repos/drupal/drupal/issues/events{/number}",
    events_url: "https://api.github.com/repos/drupal/drupal/events",
    assignees_url:
      "https://api.github.com/repos/drupal/drupal/assignees{/user}",
    branches_url:
      "https://api.github.com/repos/drupal/drupal/branches{/branch}",
    tags_url: "https://api.github.com/repos/drupal/drupal/tags",
    blobs_url: "https://api.github.com/repos/drupal/drupal/git/blobs{/sha}",
    git_tags_url: "https://api.github.com/repos/drupal/drupal/git/tags{/sha}",
    git_refs_url: "https://api.github.com/repos/drupal/drupal/git/refs{/sha}",
    trees_url: "https://api.github.com/repos/drupal/drupal/git/trees{/sha}",
    statuses_url: "https://api.github.com/repos/drupal/drupal/statuses/{sha}",
    languages_url: "https://api.github.com/repos/drupal/drupal/languages",
    stargazers_url: "https://api.github.com/repos/drupal/drupal/stargazers",
    contributors_url: "https://api.github.com/repos/drupal/drupal/contributors",
    subscribers_url: "https://api.github.com/repos/drupal/drupal/subscribers",
    subscription_url: "https://api.github.com/repos/drupal/drupal/subscription",
    commits_url: "https://api.github.com/repos/drupal/drupal/commits{/sha}",
    git_commits_url:
      "https://api.github.com/repos/drupal/drupal/git/commits{/sha}",
    comments_url:
      "https://api.github.com/repos/drupal/drupal/comments{/number}",
    issue_comment_url:
      "https://api.github.com/repos/drupal/drupal/issues/comments{/number}",
    contents_url: "https://api.github.com/repos/drupal/drupal/contents/{+path}",
    compare_url:
      "https://api.github.com/repos/drupal/drupal/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/drupal/drupal/merges",
    archive_url:
      "https://api.github.com/repos/drupal/drupal/{archive_format}{/ref}",
    downloads_url: "https://api.github.com/repos/drupal/drupal/downloads",
    issues_url: "https://api.github.com/repos/drupal/drupal/issues{/number}",
    pulls_url: "https://api.github.com/repos/drupal/drupal/pulls{/number}",
    milestones_url:
      "https://api.github.com/repos/drupal/drupal/milestones{/number}",
    notifications_url:
      "https://api.github.com/repos/drupal/drupal/notifications{?since,all,participating}",
    labels_url: "https://api.github.com/repos/drupal/drupal/labels{/name}",
    releases_url: "https://api.github.com/repos/drupal/drupal/releases{/id}",
    deployments_url: "https://api.github.com/repos/drupal/drupal/deployments",
    created_at: "2009-01-04T13:53:32Z",
    updated_at: "2024-05-15T15:53:47Z",
    pushed_at: "2024-05-15T15:53:40Z",
    git_url: "git://github.com/drupal/drupal.git",
    ssh_url: "git@github.com:drupal/drupal.git",
    clone_url: "https://github.com/drupal/drupal.git",
    svn_url: "https://github.com/drupal/drupal",
    homepage: "https://drupal.org/project/drupal",
    size: 376855,
    stargazers_count: 4019,
    watchers_count: 4019,
    language: "PHP",
    has_issues: false,
    has_projects: true,
    has_downloads: true,
    has_wiki: false,
    has_pages: false,
    has_discussions: false,
    forks_count: 1905,
    mirror_url: "http://git.drupal.org/project/drupal.git",
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: "public",
    forks: 1905,
    open_issues: 0,
    watchers: 4019,
    default_branch: "11.x",
    permissions: [Object],
  },
];
